facemash/urls.py
from django.conf.urls import patterns, url
from facemash import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    # url(r'^(?P<question_id>\d+)/$',views.detail,name='detail'),
    # url(r'^(?P<question_id>\d+)/results/$',views.results,name='results'),
    url(r'^vote/(?P<lose_id>\d+)/(?P<win_id>\d+)/$',views.vote,name='vote'),
    url(r'^(?P<gender>[mf])/choose/$',views.choose,name='choose'),
    url(r'^(?P<gender>[mf])/rankings/$',views.board,name='board'),

)

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>\d+)/results/$',views.results,name='results'),
    url(r'^(?P<question_id>\d+)/vote/$',views.vote,name='vote')
)

testproj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


# Examples:
# url(r'^$', 'testproj.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),


urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls',namespace = 'polls')),
    url(r'^social/',include('social.urls',namespace = 'social')),
    url(r'^hackernews/',include('hackernews.urls',namespace = 'hackernews')),
    url(r'^facemash/',include('facemash.urls',namespace = 'facemash')),
    url(r'^admin/', include(admin.site.urls))
)

facemash/models.py
from django.db import models

class User(models.Model):

	gender_chioces = (('m','Male'),('f','Female'))

	user_rating = models.FloatField(default=1500)
	user_name = models.CharField(max_length=100)
	user_id = models.BigIntegerField(default=0)
	user_gender = models.CharField(choices=gender_chioces,max_length=1)
	user_picture = models.CharField(max_length=200,default='https://pbs.twimg.com/profile_images/3700906677/620e0c1391e55d928f4a7d34efd19e89.png')

	def user_id_string(self):
		return str(self.user_id)

facemash/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from facemash.models import User
from django.core.urlresolvers import reverse
import random
import sys
import json

def index(request):
	return render(request,'facemash/index.html',{})

def choose(request,gender):
	u_list = User.objects.filter(user_gender=gender).order_by('user_rating')
	n=0
	m=0
	while n == m:
		n = random.randint(0,len(u_list)-1)
		m = random.randint(0,len(u_list)-1)
	user_A = u_list[n]
	user_B = u_list[m]
	# if n == 0:
	# 	user_B = u_list[n+1]
	# elif n == len(u_list)-1:
	# 	user_B = u_list[len(u_list-2)]
	# else:
	# 	if abs(user_A.user_rating - u_list[n+1].user_rating) < abs(user_A.user_rating - u_list[n-1].user_rating):
	# 		user_B = u_list[n+1]
	# 	else:
	# 		user_B = u_list[n-1]
	context = {'user_A':user_A,'user_B':user_B,'gender':gender}
	return render(request,'facemash/choose.html',context)


def vote(request,lose_id,win_id):
	if len(lose_id) > 0 and len(win_id) > 0:
		lose_user = get_object_or_404(User,user_id=lose_id) # A
		win_user  = get_object_or_404(User,user_id=win_id)  # B
		old_A = lose_user.user_rating
		old_B = win_user.user_rating
		expected_A = 1/float(1+10**((win_user.user_rating-lose_user.user_rating)/400))
		expected_B = 1-expected_A
		score_A = 0
		score_B = 1
		new_score_A = lose_user.user_rating + 32*(score_A-expected_A)
		new_score_B = win_user.user_rating + 32*(score_B-expected_B)
		lose_user.user_rating = new_score_A
		win_user.user_rating = new_score_B
		lose_user.save()
		win_user.save()
		l = [old_A,new_score_A,expected_A,score_A]
		w = [old_B,new_score_B,expected_B,score_B]
		# print >>sys.stderr, 'Lose: '+str(old_A)+'-->'+str(lose_user.user_rating)
		# print >>sys.stderr, 'Win: '+str(old_B)+'-->'+str(win_user.user_rating)
		print >>sys.stderr,json.dumps(l)
		print >>sys.stderr,json.dumps(w)

		return HttpResponseRedirect(reverse('facemash:choose',args=(win_user.user_gender,)))
	else:
		return HttpResponseRedirect(reverse('facemash:choose'))

def board(request,gender):
	u_list = User.objects.filter(user_gender=gender).order_by('-user_rating')
	u_list = u_list[:10]
	context = {'u_list':u_list}
	return render(request,'facemash/board.html',context)

facemash/templates/facemash/board.html
{% load staticfiles %}
{% load facemash_extras %}
<link rel="stylesheet" type="text/css" href="{% static 'facemash/board.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'facemash/font-awesome/css/font-awesome.min.css' %}">
<link href="{% static 'facemash/bitter.css' %}" rel='stylesheet' type='text/css'>

<html>
	<body>
		<div id="header">
			<a id="title" href="{% url 'facemash:choose' u_list.1.user_gender %}">Choosr</a>
		</div>
		<div id="rank_div">
			<ul id="rank_ol">
				{% for user in u_list %}
					<li>
						<div class="user_element">
							<img src="{% static 'facemash/images/cropped/'|addstr:user.user_id|addstr:'.jpg' %}" width="65" height="65">
							<div class="user_name" href="">{{ user.user_name }}</div>
							<div class="rank_number">{{ forloop.counter|romanize:'upper' }}</div>
						</div>
					</li>
				{% endfor %}
			</ol>
		</div>
	</body>
</html>

facemash/templates/facemash/choose.html
{% load staticfiles %}
{% load facemash_extras %}

<link rel="stylesheet" type="text/css" href="{% static 'facemash/choose.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'facemash/font-awesome/css/font-awesome.min.css' %}">
<link href="{% static 'facemash/bitter.css' %}" rel='stylesheet' type='text/css'>

<html>
	<body>
		{% if gender %}
			<div id="header">
				<form action="{% url 'facemash:board' user_A.user_gender %}">
				    <input id="rank_button" type="submit" value="Rankings">
				</form>
				<a id="title" href="{% url 'facemash:choose' user_A.user_gender %}">Choosr</a>
			</div>
			<div id="outer_container">
				<div style="float:left;margin-left:20px;" class="inner_container">
					<a href="{% url 'facemash:vote' user_B.user_id_string user_A.user_id_string %}" id="left_img" ><img id="left" src='{% static "facemash/images/cropped/"|addstr:user_A.user_id|addstr:".jpg" %}' height="300" width="300" style="max-height: 100%; max-width: 100%;"></a>
				</div>
				<div style="float:right;margin-right:20px;" class="inner_container">
					<a href="{% url 'facemash:vote' user_A.user_id_string user_B.user_id_string %}" id="right_img" ><img id="right" src='{% static "facemash/images/cropped/"|addstr:user_B.user_id|addstr:".jpg" %}' height="300" width="300" style="max-height: 100%; max-width: 100%;" ></a>

				</div>
			</div>
			<div id="arrow_outer_container">
				<div style="float:left;" class="arrow_inner_container">
					<a href="{% url 'facemash:vote' user_B.user_id_string user_A.user_id_string %}" id="left_img" ><i class="fa fa-arrow-left" style="font-size:200;color:#DF514B;" id="left_arrow"></i></a>
				</div>
				<div style="float:right;" class="arrow_inner_container">
					<a href="{% url 'facemash:vote' user_A.user_id_string user_B.user_id_string %}" id="right_img" ><i class="fa fa-arrow-right" style="font-size:200;color:#DF514B;" id="right_arrow"></i></a>
				</div>
			</div>
			
			<script type="text/javascript">
				// var img = document.images
				// for (var i=0; i<img.length; i++) {
				// 	var a = img[i];
				// 	if ( a.naturalWidth > a.naturalHeight ){
				// 		a.height = "300";
				// 	}else{
				// 		a.width = "300";
				// 	}
				// }
				function leftArrowPressed() {
				   document.getElementById('left_img').click();
				}

				function rightArrowPressed() {
				   document.getElementById('right_img').click();
				}



				document.onkeydown = function(evt) {
				    evt = evt || window.event;
				    switch (evt.keyCode) {
				        case 37:
				            leftArrowPressed();
				            break;
				        case 39:
				            rightArrowPressed();
				            break;
				    }
				};
			</script>
		{% endif %}
	</body>
</html>

facemash/templates/facemash/index.html
{% load staticfiles %}
<html>
	<h1>What do you want to see?</h1>
	<form action="{% url 'facemash:choose' 'm' %}" method="post">
		{% csrf_token %}
		<input type="submit" value="Male"/>
	</form>
	<form action="{% url 'facemash:choose' 'f' %}" method="post">
		{% csrf_token %}
		<input type="submit" value="Female"/>		
	</form>
</html>