polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>\d+)/results/$',views.results,name='results'),
    url(r'^(?P<question_id>\d+)/vote/$',views.vote,name='vote')
)

social/urls.py
from django.conf.urls import patterns, url
from social import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^post/$',views.post,name='post'),
	url(r'^signup/$',views.signup,name='signup')
)

testproj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


# Examples:
# url(r'^$', 'testproj.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),


urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls',namespace = 'polls')),
    url(r'^social/',include('social.urls',namespace = 'social')),
    url(r'^hackernews/',include('hackernews.urls',namespace = 'hackernews')),
    url(r'^facemash/',include('facemash.urls',namespace = 'facemash')),
    url(r'^admin/', include(admin.site.urls))
)

social/models.py
from django.db import models
from django.utils import timezone
import math

class User(models.Model):
	username = models.CharField(max_length=20)
	password = models.CharField(max_length=50)
	first_name = models.CharField(max_length=20)
	last_name = models.CharField(max_length=20)

	def __str__(self):
		return self.username

	def action_post(self,text):
		p = Post(post_user=self,post_date=timezone.now(),post_text=text)
		p.save()
		return p

	def kudos(self):
		posts = self.post_set.all()
		return int(math.fsum([p.post_kudos for p in posts]))


class Post(models.Model):
	post_date = models.DateTimeField()
	post_text = models.CharField(max_length=200)
	post_user = models.ForeignKey(User)
	post_kudos = models.IntegerField(default=0)

	def __str__(self):
		return self.post_text[:10] + '...'

social/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from social.models import User,Post
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def check_user(request):
	try:
		username = request.POST['user']
		try:
			username = User.objects.get(username=username)
		except User.DoesNotExist:
			username = ''
	except KeyError:
		try:
			username = request.session['user_id']
			try:
				username = User.objects.get(id=username)
			except User.DoesNotExist:
				username = ''
		except KeyError:
			username = ''
	return username

def index(request):
	post_list = Post.objects.order_by('-post_date')
	u = check_user(request)
	should_log_in = bool(request.POST.get('should_log_in',True))
	if should_log_in == False:
		request.session.flush()
		request.session['logged_in'] = False
		logged_in = False
	else:
		logged_in = request.session.get('logged_in',False)
		if u != '' and logged_in == False:
			try:
				if u.password == request.POST['pass']:
					request.session.set_expiry(7200)
					request.session['user_id'] = u.id
					request.session['logged_in'] = True
					u = u.username
				else:
					u = ''
			except KeyError:
				u = ''
		logged_in = request.session.get('logged_in',False)
	return render(request,'social/index.html',{'post_list':post_list,'username':u,'logged_in':logged_in})

def post(request):
	u = check_user(request)
	post = ''
	try:
		post = request.POST['post_text']
	except KeyError:
		post = ''
	if u != '' and post != '':
		u.action_post(post)
	return HttpResponseRedirect(reverse('social:index'))

def signup(request):
	should_sign_up = bool(request.POST.get('should_sign_up',''))
	if should_sign_up == True:
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		first_name = request.POST.get('first_name','')
		last_name = request.POST.get('last_name','')
		old_users = [i.username for i in User.objects.all()]
		if username != '' and password != '' and first_name != '' and last_name != '' and len(password) >= 8 and username not in old_users:
			u = User(username=username,password=password,first_name=first_name,last_name=last_name)
			u.save()
			return HttpResponseRedirect(reverse('social:index'))
		else:
			return render(request,'social/sign_up.html',{})
	else:
		return render(request,'social/sign_up.html',{})



	

social/templates/social/index.html
<head>
	<title id>SOCIAL</title>
	{% load staticfiles %}
	<link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'social/index_style.css' %}">
</head>
<body>
	<form action="{% url 'social:index' %}" method="post">
	{% csrf_token %}
		{% if logged_in == True %}
			<div id="topBar">		
				<input id="logoutButton" type="submit" value="Log out">
				<input type="hidden" name="should_log_in" value=""/>
				<div id="topBarHeader">
					Hello there, <b>{{ username }}</b> 
				</div>
			</div>
		{% endif %}
	</form>
		<div id="titleWrapper">
			<div id="mainHeader">SOCIAL</div>
			<br />
			<div id="subHeader">The minimal social network</div>
		</div>
	<br />
	<div id="contentWrapper">
		{% if logged_in == True %}
			<form action="{% url 'social:post' %}" method="post">
			{% csrf_token %}
				<textarea id="commentArea" name="post_text" placeholder="Tell me your secrets..." cols="100" rows="3"></textarea>
				<br />
				<input class="genButton" id="postButton" type="submit" value="Post" />
			</form>
			
		{% endif %}

		{% for post in post_list %}
			<div class="postWrapper">
				<div class="postText">
					{{ post.post_text }}<br />
					{# <b>{{post.post_kudos}} Kudo{{post.post_kudos|pluralize}}</b> -  #}
				</div>
				<div class="kudoWrapper">
					{{post.post_kudos}} 
				</div>
				<div class="postInfo">Posted by <b>{{ post.post_user.username }}</b> at {{ post.post_date}}</div>
				
			</div>
			
		{% endfor %}
		{% if logged_in == False %}
		<div id="loginWrapper">
			<form action="{% url 'social:index' %}" method="post">
			{% csrf_token %}
			{% if logged_in == False %}
				<div id="usernameWrapper"><span>Username: <input class="loginTextBox" type="text" name="user"/></span></div>
				<div id="passwordWrapper"><span>Password: <input class="loginTextBox" type="password" name="pass"/></span></div>
				<input type="hidden" name="should_log_in" value="True"/>
				<br />
				<input class="genButton" id="footButton_1" type="submit" value="Login">
			{% endif %}
				
			</form>

			{% if logged_in == False %}
			<form action="{% url 'social:signup'%}" method="post">
			{% csrf_token %}
				<input class="genButton" id="footButton_2" type="submit" value="Sign Up">
			</form>
			{% endif %}
		</div>
		{% endif %}
	</div>
</body>

social/templates/social/sign_up.html
<head>
	<title>SOCIAL</title>
</head>
<body>
	<h1>SOCIAL - The minimal social network</h1>
	<hr />
	<br />
	<h2>Sign Up</h2>
	<br />
	<form action="{% url 'social:signup' %}" method="post">
	{% csrf_token %}
		<input type="hidden" value="True" name="should_sign_up"/>
		Username:<br /><input type="text" name="username"/><br />
		Password: ( at least eight characters )<br /><input type="password" name="password" /><br />
		First name:<br /><input type="text" name="first_name"/><br />
		Last name:<br /><input type="text" name="last_name" />
		<br /><input type="submit" value="Sign Up" />
	</form>
</body>